const db = require("../db");
const { createEvent } = require("../services/eventService");
const { createAlert } = require("../services/alertService");
const {
  normalizeText,
  normalizeKey,
  requireFields,
  sendDbError,
  validateEnum,
  validateNumber,
} = require("../utils/http");

const QUALITY_FLAGS = ["good", "warning", "error"];

const DEFAULT_SENSOR_RANGES = {
  temperature: { min: 18, max: 26 },
  humidity: { min: 30, max: 60 },
  motion: { min: 0, max: 1 },
  smoke: { min: 0, max: 10 },
  light: { min: 100, max: 800 },
  energy: { min: 0, max: 2.5 },
  open_close: { min: 0, max: 1 },
};

function getRangeForSensor(sensor) {
  const fallback = DEFAULT_SENSOR_RANGES[sensor.sensor_type] || { min: 0, max: 100 };
  const min = sensor.normal_min !== null ? Number(sensor.normal_min) : fallback.min;
  const max = sensor.normal_max !== null ? Number(sensor.normal_max) : fallback.max;

  if (Number.isNaN(min) || Number.isNaN(max) || min > max) {
    return fallback;
  }

  return { min, max };
}

function roundReading(value) {
  return Number(value.toFixed(2));
}

function randomBetween(min, max) {
  return min + Math.random() * (max - min);
}

function buildSimulatedReading(sensor) {
  const { min, max } = getRangeForSensor(sensor);
  const width = Math.max(max - min, 1);
  const chance = Math.random();

  if (chance < 0.82) {
    return {
      reading_value: roundReading(randomBetween(min, max)),
      quality_flag: "good",
    };
  }

  if (chance < 0.95) {
    const direction = Math.random() < 0.5 ? -1 : 1;
    const offset = randomBetween(width * 0.03, width * 0.15);

    return {
      reading_value: roundReading(direction < 0 ? min - offset : max + offset),
      quality_flag: "warning",
    };
  }

  const direction = Math.random() < 0.5 ? -1 : 1;
  const offset = randomBetween(width * 0.2, width * 0.45);

  return {
    reading_value: roundReading(direction < 0 ? min - offset : max + offset),
    quality_flag: "error",
  };
}

function buildRandomReadingTime() {
  const thirtyDaysMs = 30 * 24 * 60 * 60 * 1000;
  return new Date(Date.now() - Math.random() * thirtyDaysMs);
}

async function getSensorContext(sensorId) {
  const sensorResult = await db.query(
    `
    SELECT s.sensor_id, s.sensor_type, s.normal_min, s.normal_max, s.device_id,
           r.home_id
    FROM Sensor s
    JOIN Device d ON s.device_id = d.device_id
    JOIN Room r ON d.room_id = r.room_id
    WHERE s.sensor_id = $1
    `,
    [sensorId],
  );

  return sensorResult.rows[0] || null;
}

async function getAllSensorContexts(client) {
  const result = await client.query(
    `
    SELECT s.sensor_id, s.sensor_type, s.normal_min, s.normal_max, s.device_id,
           r.home_id
    FROM Sensor s
    JOIN Device d ON s.device_id = d.device_id
    JOIN Room r ON d.room_id = r.room_id
    ORDER BY s.sensor_id ASC
    `,
  );

  return result.rows;
}

async function insertReading(sensor, readingValue, qualityFlag, eventType) {
  const result = await db.query(
    `
    INSERT INTO SensorReading (sensor_id, reading_time, reading_value, quality_flag)
    VALUES ($1, NOW(), $2, $3)
    RETURNING *
    `,
    [sensor.sensor_id, readingValue, qualityFlag],
  );

  const reading = result.rows[0];

  await createEvent(
    sensor.home_id,
    sensor.device_id,
    eventType,
    `New reading generated for sensor "${sensor.sensor_type}"`,
  );

  const value = Number(reading.reading_value);
  const min = sensor.normal_min !== null ? Number(sensor.normal_min) : null;
  const max = sensor.normal_max !== null ? Number(sensor.normal_max) : null;

  const isBelow = min !== null && value < min;
  const isAbove = max !== null && value > max;

  if (isBelow || isAbove) {
    await createAlert(
      sensor.home_id,
      sensor.sensor_id,
      "abnormal_reading",
      qualityFlag === "error" ? "high" : "medium",
    );
  }

  return reading;
}

async function insertReadingBatch(client, rows) {
  const values = [];
  const params = [];

  rows.forEach((row, index) => {
    const start = index * 4;
    values.push(`($${start + 1}, $${start + 2}, $${start + 3}, $${start + 4})`);
    params.push(row.sensor_id, row.reading_time, row.reading_value, row.quality_flag);
  });

  await client.query(
    `
    INSERT INTO SensorReading (sensor_id, reading_time, reading_value, quality_flag)
    VALUES ${values.join(", ")}
    `,
    params,
  );
}

async function createBulkEvents(client, homeIds, count) {
  for (const homeId of homeIds) {
    await client.query(
      `
      INSERT INTO Event (home_id, device_id, event_type, event_time, description)
      VALUES ($1, NULL, $2, NOW(), $3)
      `,
      [
        homeId,
        "bulk_readings_simulated",
        `${count} readings were generated by the IoT simulator`,
      ],
    );
  }
}

async function createBulkAlerts(client, abnormalSensors) {
  const sensors = Array.from(abnormalSensors.values());

  for (const sensor of sensors) {
    await client.query(
      `
      INSERT INTO Alert (home_id, sensor_id, alert_type, severity, created_at, is_resolved)
      SELECT $1, $2, 'abnormal_reading', $3, NOW(), FALSE
      WHERE NOT EXISTS (
        SELECT 1
        FROM Alert
        WHERE home_id = $1
          AND sensor_id = $2
          AND alert_type = 'abnormal_reading'
          AND is_resolved = FALSE
      )
      `,
      [sensor.home_id, sensor.sensor_id, sensor.severity],
    );
  }
}

exports.getReadingsBySensor = async (req, res) => {
  try {
    const sensorId = req.params.sensorId;

    const result = await db.query(
      `
      SELECT * FROM SensorReading
      WHERE sensor_id = $1
      ORDER BY reading_time DESC
      `,
      [sensorId],
    );

    res.json(result.rows);
  } catch (error) {
    console.error("GET READINGS ERROR:", error.message);
    sendDbError(res, error);
  }
};

exports.createReading = async (req, res) => {
  try {
    const sensor_id = req.body.sensor_id;
    const reading_value = req.body.reading_value;
    const quality_flag = normalizeKey(req.body.quality_flag);

    if (
      !requireFields(res, [
        { label: "Sensor", value: sensor_id },
        { label: "Reading value", value: reading_value },
        { label: "Quality", value: quality_flag },
      ])
    ) {
      return;
    }

    if (
      !validateEnum(res, quality_flag, QUALITY_FLAGS, "quality") ||
      !validateNumber(res, reading_value, "Reading value")
    ) {
      return;
    }

    const sensor = await getSensorContext(sensor_id);

    if (!sensor) {
      return res.status(404).json({ error: "Sensor not found." });
    }

    const reading = await insertReading(
      sensor,
      reading_value,
      quality_flag,
      "reading_added",
    );

    res.status(201).json({
      message: "Reading created successfully",
      reading,
    });
  } catch (error) {
    console.error("CREATE READING ERROR:", error.message);
    sendDbError(res, error);
  }
};

exports.simulateReading = async (req, res) => {
  try {
    const sensor_id = req.body.sensor_id;

    if (
      !requireFields(res, [
        { label: "Sensor", value: sensor_id },
      ])
    ) {
      return;
    }

    const sensor = await getSensorContext(sensor_id);

    if (!sensor) {
      return res.status(404).json({ error: "Sensor not found." });
    }

    const simulated = buildSimulatedReading(sensor);
    const reading = await insertReading(
      sensor,
      simulated.reading_value,
      simulated.quality_flag,
      "reading_simulated",
    );

    res.status(201).json({
      message: "Simulated reading generated successfully",
      reading,
    });
  } catch (error) {
    console.error("SIMULATE READING ERROR:", error.message);
    sendDbError(res, error);
  }
};

exports.simulateBulkReadings = async (req, res) => {
  const client = await db.connect();

  try {
    const requestedCount = req.body.count || 5000;

    if (!validateNumber(res, requestedCount, "Reading count")) {
      return;
    }

    const count = Number(requestedCount);

    if (count < 1 || count > 50000) {
      return res.status(400).json({
        error: "Reading count must be between 1 and 50000.",
      });
    }

    await client.query("BEGIN");

    const sensors = await getAllSensorContexts(client);

    if (sensors.length === 0) {
      await client.query("ROLLBACK");
      return res.status(400).json({
        error: "Create at least one device with sensors before generating readings.",
      });
    }

    const batchSize = 500;
    const abnormalSensors = new Map();
    const homeIds = new Set();
    let insertedCount = 0;

    for (let index = 0; index < count; index += batchSize) {
      const batch = [];
      const limit = Math.min(index + batchSize, count);

      for (let rowIndex = index; rowIndex < limit; rowIndex += 1) {
        const sensor = sensors[rowIndex % sensors.length];
        const simulated = buildSimulatedReading(sensor);

        homeIds.add(sensor.home_id);

        if (simulated.quality_flag !== "good") {
          const existing = abnormalSensors.get(sensor.sensor_id);
          const severity =
            simulated.quality_flag === "error" || existing?.severity === "high"
              ? "high"
              : "medium";

          abnormalSensors.set(sensor.sensor_id, {
            home_id: sensor.home_id,
            sensor_id: sensor.sensor_id,
            severity,
          });
        }

        batch.push({
          sensor_id: sensor.sensor_id,
          reading_time: buildRandomReadingTime(),
          reading_value: simulated.reading_value,
          quality_flag: simulated.quality_flag,
        });
      }

      await insertReadingBatch(client, batch);
      insertedCount += batch.length;
    }

    await createBulkEvents(client, homeIds, insertedCount);
    await createBulkAlerts(client, abnormalSensors);

    await client.query("COMMIT");

    res.status(201).json({
      message: `${insertedCount} simulated readings generated successfully`,
      inserted_count: insertedCount,
      sensor_count: sensors.length,
      alert_sensor_count: abnormalSensors.size,
    });
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("SIMULATE BULK READINGS ERROR:", error.message);
    sendDbError(res, error);
  } finally {
    client.release();
  }
};
